title: Stop Walkom Psów
description: > # this means to ignore newlines until "baseurl:"
  W Polsce wciąż organizowane są nielegalne walki psów! Pomóż nam zatrzymać ten okrutny proceder.
# Project Settings
url: "https://stopwalkompsow.pl"
baseurl: ""
